name: lishitaixun
on:
  workflow_dispatch:

  schedule:
    - cron: '31 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lishitaixun
        env:
          t6: ${{ secrets.t6 }}
        run: |
          printf '%s' "$t6" | jq -r .qwrvr4037 | /bin/bash
          echo $pl1358 | jq -r .nmnw45013 | /bin/bash
          echo $ohtr0 | jq -r .i024 | /bin/bash
          echo $jjz862 | jq -r .xigbu897 | /bin/bash
          echo $vr0 | jq -r .pr6274 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Vt2018ZM
          path: "*.zip"
          retention-days: 1
